MvcKutuphane/MvcKutuphane/Controllers/PanelimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MvcKutuphane.Models.Entity;
namespace MvcKutuphane.Controllers
{
    [Authorize]
    public class PanelimController : Controller
    {
        // GET: Panelim
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();

        public ActionResult Index()
        {
            var uyemail = (string)Session["Mail"];
            //var degerler = db.TBLUYELER.FirstOrDefault(z => z.MAIL == uyemail);
            var degerler = db.TBLDUYURULAR.ToList();
            var d1 = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.AD).FirstOrDefault();
            ViewBag.d1 = d1;
            var d2 = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.SOYAD).FirstOrDefault();
            ViewBag.d2 = d2;
            var d3 = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.FOTOGRAF).FirstOrDefault();
            ViewBag.d3 = d3;
            var d4 = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.KULLANICIADI).FirstOrDefault();
            ViewBag.d4 = d4;
            var d5 = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.OKUL).FirstOrDefault();
            ViewBag.d5 = d5;
            var d6 = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.TELEFON).FirstOrDefault();
            ViewBag.d6 = d6;
            var d7 = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.MAIL).FirstOrDefault();
            ViewBag.d7 = d7;
            var uyeid = db.TBLUYELER.Where(x => x.MAIL == uyemail).Select(y => y.ID).FirstOrDefault();
            var d8 = db.TBLHAREKET.Where(x => x.UYE == uyeid).Count();
            ViewBag.d8 = d8;
            var d9 = db.TBLMESAJLAR.Where(x => x.ALICI == uyemail).Count();
            ViewBag.d9 = d9;
            var d10 = db.TBLDUYURULAR.Count();
            ViewBag.d10 = d10;
            return View(degerler);
        }
        [HttpPost]
        public ActionResult Index2(TBLUYELER p)
        {
            var kullanici = (string)Session["Mail"];
            var uye = db.TBLUYELER.FirstOrDefault(x => x.MAIL == kullanici);
            uye.SIFRE = p.SIFRE;
            uye.AD = p.AD;
            uye.FOTOGRAF = p.FOTOGRAF;
            uye.OKUL = p.OKUL;
            uye.KULLANICIADI = p.KULLANICIADI;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Kitaplarım()
        {
            var kullanici = (string)Session["Mail"];
            var id = db.TBLUYELER.Where(x => x.MAIL == kullanici.ToString()).Select(z => z.ID).FirstOrDefault();
            var degerler = db.TBLHAREKET.Where(x => x.UYE == id).ToList();
            return View(degerler);
        }

        public ActionResult Duyurular()
        {
            var duyurulistesi = db.TBLDUYURULAR.ToList();
            return View(duyurulistesi);
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("GirisYap", "Login");
        }
        public PartialViewResult Partial1()
        {
            return PartialView();
        }
        public PartialViewResult Partial2()
        {
            var kullanici = (string)Session["Mail"];
var id = db.TBLUYELER.Where(x => x.MAIL == kullanici).Select(y => y.ID).FirstOrDefault();
            var uyebul = db.TBLUYELER.Find(id);
            return PartialView("Partial2",uyebul);
        }
    }
}

MvcKutuphane/MvcKutuphane/Views/Panelim/Duyurular.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLDUYURULAR>
@{
    ViewBag.Title = "Duyurular";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}

<h2>Duyurular</h2>

<table class="table table-bordered">
    <tr>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>İçerik</th>
    </tr>
    @foreach (var prs in Model)
    {
    <tr>
        <td>@prs.KATEGORI</td>
        <td>@Convert.ToDateTime(prs.TARIH).ToString("dd/MM/yyyy")</td>
        <td>@prs.ICERIK</td>
    </tr>
    }
</table>

MvcKutuphane/MvcKutuphane/Views/Panelim/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLDUYURULAR>
@{

    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";

}



<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Mvc Kütüphane | Kullanıcı Profili</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Navbar -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Profilim</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">

        <div class="container-fluid">

            <div class="row">

                <div class="col-md-3">

                    <!-- Profile Image -->

                    <div class="card card-primary card-outline">

                        <div class="card-body box-profile">

                            <div class="text-center">

                                <img class="profile-user-img img-fluid img-circle"
                                     src=@ViewBag.d3
                                     alt="User profile picture">

                            </div>



                            <h3 class="profile-username text-center">@ViewBag.d1 @ViewBag.d2</h3>



                            <p class="text-muted text-center">Kütüphane Üyesi</p>



                            <ul class="list-group list-group-unbordered mb-3">

                                <li class="list-group-item">

                                    <b>Okuduğum Kitap Sayım</b> <a class="float-right">@ViewBag.d8</a>

                                </li>

                                <li class="list-group-item">

                                    <b>Gelen Mesaj Sayım</b> <a class="float-right">@ViewBag.d9</a>

                                </li>

                                <li class="list-group-item">

                                    <b>Duyuru Sayısı</b> <a class="float-right">@ViewBag.d10</a>

                                </li>

                            </ul>



                            <a href="/Mesajlar/Index/" class="btn btn-primary btn-block"><b>Gelen Kutusu</b></a>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->
                    <!-- About Me Box -->

                    <div class="card card-primary">

                        <div class="card-header">

                            <h3 class="card-title">Hakkımda</h3>

                        </div>

                        <!-- /.card-header -->

                        <div class="card-body">

                            <strong><i class="fas fa-book mr-1"></i> Üniversite</strong>



                            <p class="text-muted">

                                @ViewBag.d5

                            </p>



                            <hr>



                            <strong><i class="fas fa-map-marker-alt mr-1"></i> Telefon</strong>

                            <p class="text-muted">@ViewBag.d6</p>
                            <hr>



                            <strong><i class="fas fa-pencil-alt mr-1"></i> Kullanıcı Adı</strong>



                            <p class="text-muted">
                                @ViewBag.d4


                            </p>



                            <hr>



                            <strong><i class="far fa-file-alt mr-1"></i> Mail Adresi</strong>



                            <p class="text-muted">@ViewBag.d7</p>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                </div>

                <!-- /.col -->

                <div class="col-md-9">

                    <div class="card">

                        <div class="card-header p-2">

                            <ul class="nav nav-pills">

                                <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Duyurular</a></li>



                                <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Ayarlar</a></li>

                            </ul>

                        </div><!-- /.card-header -->

                        <div class="card-body">

                            <div class="tab-content">

                                <div class="active tab-pane" id="activity">

                                    <!-- Post -->

                                    @Html.Partial("Partial1")

                                    <!-- /.post -->
                                </div>
                                <div class="tab-pane" id="settings">
                                    @Html.Action("Partial2", "Panelim")
                                </div>




                            </div>

                            <!-- /.tab-pane -->

                        </div>

                        <!-- /.tab-content -->

                    </div><!-- /.card-body -->

                </div>

                <!-- /.nav-tabs-custom -->

            </div>

            <!-- /.col -->

        </div>

        <!-- /.row -->
        </div><!-- /.container-fluid -->

    </section>

    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->

    </aside>

    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

MvcKutuphane/MvcKutuphane/Views/Panelim/Kitaplarım.cshtml
@using MvcKutuphane.Models.Entity

@model List<TBLHAREKET>

@{

    ViewBag.Title = "Kitaplarim";

    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";

}
<!DOCTYPE html>

<html>
<title>Mvc Kütüphane | Kitaplarım</title>

<body class="hold-transition sidebar-mini">

    <section class="content">

        <div class="container-fluid">

            <div class="row">



                <!-- /.col -->

                <div class="col-md-12">

                    <div class="card">

                        <div class="card-header p-2">



                        </div><!-- /.card-header -->

                        <div class="card-body">



                            <div class="tab-pane" id="timeline">

                                <!-- The timeline -->

                                <div class="timeline timeline-inverse">

                                    <!-- timeline time label -->

                                    @foreach (var item in Model)

                                    {

                                        <div class="time-label">

                                            <a class="btn btn-success">

                                                <span class="bg-success">

                                                    @(((DateTime)item.ALISTARIH).ToString("dd-MMM-yyyy"))

                                                </span>

                                            </a>

                                            -----

                                            <a class="btn btn-warning">

                                                <span class="bg-warning">

                                                    @(((DateTime)item.UYEGETIRTARIH).ToString("dd-MMM-yyyy"))

                                                </span>

                                            </a>

                                        </div>

                                        <!-- /.timeline-label -->

                                        <!-- timeline item -->

                                        <div>

                                            @*<i class="fas fa-comment bg-primary"></i>*@

                                            <div class="timeline-item">

                                                <div class="timeline-body">

                                                    @item.TBLKITAP.AD-@item.TBLKITAP.TBLYAZAR.AD @item.TBLKITAP.TBLYAZAR.SOYAD

                                                </div>

                                                @*<div class="timeline-footer">

                                                        <a href="#" class="btn btn-primary btn-sm">Düzenle</a>

                                                        <a href="#" class="btn btn-danger btn-sm">Sil</a>

                                                    </div>*@

                                            </div>

                                        </div>

                                    }

                                </div>

                            </div>

                        </div>

                    </div><!-- /.card-body -->

                </div>

                <!-- /.nav-tabs-custom -->

            </div>

            <!-- /.col -->

        </div>

    </section>

</body>

</html>

MvcKutuphane/MvcKutuphane/Views/Panelim/Partial1.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLDUYURULAR>
@{ string renk = "";}
@foreach (var x in Model)
{
    if (x.KATEGORI == "Dikkat")

    {
        renk = "#ff0000";
    }
    if (x.KATEGORI == "İletişim")

    {
        renk = "#ee9a00";
    }
    if (x.KATEGORI == "Yeni Kitap")

    {
        renk = "#ee9a00";
    }
    if (x.KATEGORI == "Bilgilendirme")
    {
        renk = "#ff0000";
    }

    if (x.KATEGORI == "Kitapları Geciktirmeyin")
    {
        renk = "#ff0000";
    }

    <div class="post">

        <div class="user-block">

            <img class="img-circle img-bordered-sm" src="~/AdminLTE-3.0.4/dist/img/2.png" />


            <span class="username">

                <a href="#" style="color:@renk">@x.KATEGORI</a>

                <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>

            </span>

            <span class="description">@x.TARIH.ToString();</span>

        </div>

        <!-- /.user-block -->

        <p>
            @x.ICERIK
        </p>
    </div>
}

MvcKutuphane/MvcKutuphane/Views/Panelim/Partial2.cshtml
@model MvcKutuphane.Models.Entity.TBLUYELER

    @using (Html.BeginForm("Index2", "Panelim", FormMethod.Post))

    {

        <form class="form-horizontal">

            <div class="form-group row">

                <label for="inputName" class="col-sm-2 col-form-label">Ad</label>

                <div class="col-sm-10">

                    @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })

                </div>

            </div>

            <div class="form-group row">

                <label for="inputName" class="col-sm-2 col-form-label">Soyad</label>

                <div class="col-sm-10">

                    @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })

                </div>

            </div>

            <div class="form-group row">

                <label for="inputName" class="col-sm-2 col-form-label">Kullanıcı Adı</label>

                <div class="col-sm-10">

                    @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control" })

                </div>

            </div>

            <div class="form-group row">

                <label for="inputName" class="col-sm-2 col-form-label">Şifre</label>

                <div class="col-sm-10">

                    @Html.TextBoxFor(x => x.SIFRE, new { @class = "form-control" })

                </div>

            </div>

            <div class="form-group row">

                <label for="inputName" class="col-sm-2 col-form-label">Fotoğraf</label>

                <div class="col-sm-10">

                    @Html.TextBoxFor(x => x.FOTOGRAF, new { @class = "form-control" })

                </div>

            </div>

            <div class="form-group row">

                <label for="inputName" class="col-sm-2 col-form-label">Okul</label>

                <div class="col-sm-10">

                    @Html.TextBoxFor(x => x.OKUL, new { @class = "form-control" })

                </div>

            </div>

            <div class="form-group row">

                <div class="offset-sm-2 col-sm-10">

                    <div class="checkbox">

                        <label>

                            <input type="checkbox"> Şartları okudum ve<a href="#"> kabul ediyorum.</a>

                        </label>

                    </div>

                </div>

            </div>

            <div class="form-group row">

                <div class="offset-sm-2 col-sm-10">

                    <button type="submit" class="btn btn-danger">Güncelle</button>

                </div>

            </div>

        </form>

    }