MvcKutuphane/MvcKutuphane/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;
namespace MvcKutuphane.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLPERSONEL.ToList();
            return View(degerler);
        }
            [HttpGet]
            public ActionResult PersonelEkle()
            {
                return View();
            }
            [HttpPost]
            public ActionResult PersonelEkle(TBLPERSONEL p)
            {
                if (!ModelState.IsValid)
                {
                    return View("PersonelEkle");
                }
                db.TBLPERSONEL.Add(p);
                db.SaveChanges();
                return View();
        }
        public ActionResult PersonelSil(int id)
        {
            var person = db.TBLPERSONEL.Find(id);
            db.TBLPERSONEL.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetir(int id)
        {
            var prs = db.TBLPERSONEL.Find(id);
            return View("PersonelGetir", prs);
        }
        public ActionResult PersonelGuncelle(TBLPERSONEL p)
        {
            var prs = db.TBLPERSONEL.Find(p.ID);
            prs.PERSONEL = p.PERSONEL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
    }
 

MvcKutuphane/MvcKutuphane/Views/Personel/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLPERSONEL>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<title>Mvc Kütüphane | Personeller</title>
<h2>Personeller</h2>

<table class="table table-bordered">
    <tr>
        <th>Personel ID</th>
        <th>Personel Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var prs in Model)
    {
        <tr>
            <td>@prs.ID</td>
            <td>@prs.PERSONEL</td>
            <td> <a href="/Personel/PersonelSil/@prs.ID" class="btn btn-danger">Sil</a> </td>
            <td> <a href="/Personel/PersonelGetir/@prs.ID" class="btn btn-success">Güncelle</a> </td>
        </tr>
    }
</table>
<a href="/Personel/PersonelEkle" class="btn btn-primary">Yeni Personel Ekle</a>

MvcKutuphane/MvcKutuphane/Views/Personel/PersonelEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLPERSONEL
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>PersonelEkle</h2>

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Personel Adı</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.PERSONEL, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PERSONEL, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Personel Ekle</button>
    </div>
</form>

MvcKutuphane/MvcKutuphane/Views/Personel/PersonelGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLPERSONEL
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(p => p.ID)
        @Html.TextBoxFor(p => p.ID, new { @class = "form-control" })
        <br />
        <label>PERSONEL ADI</label>
        @Html.LabelFor(p => p.PERSONEL)
        @Html.TextBoxFor(p => p.PERSONEL, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}